### Delete person [DELETE /users/persons/{personId}]
*Deleta todos os dados e relacionamentos vinculados ao ID da pessoa*

+ Request (application/json)
    + Headers

            Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...

+ Parameters
    + personId: 5e05d7c573b8727b1e14273f (string, required)

+ Response 200 (application/json)
    + Attributes
        <!-- include(../../responses/personDelete.apib) -->

+ Response 401 (aplication/json)
    + Attributes
        <!-- include(../../util/errorUnauthorized.apib) -->

+ Response 404 (aplication/json)
    + Attributes
        <!-- include(../../util/errorNotFound.apib) -->
