+ address: `Av. cesar finotti, 305 - Jardim Finotti, Uberlândia - MG, 38400-165, Brasil` (string, optional) - obs: Não precisa passar o endereço completo ex: `Av. Cesar Finotti, 305`
+ local_name: Edificio Alcione Zago (string, optional) - Campo para obter o nome do local e sua foto padrão, sem ele, não é possível obter fotos de um local.
