first_name: Gabriel (string, required)
last_name: Maximo (string, required)
cpf: 11721BCC027 (string, required)
address: `Av. Floriano Peixoto, 1615 - Nossa Sra. Aparecida, Uberlândia - MG, Brasil` (string, required) - Não precisa necessariamente digitar nessa formatação, pode digitar somente a avenida, assim como faz com o Uber.
local_name: t10 lab (string, required)
