+ name: Gabriel Maximo (string, required)
+ email: maximo@ufu.br (string, required) - condition: valid email
+ password: 123456 (string, required) - condition: minimum 6 characters
+ confirmPassword: 123456 (string, required)
