### Create user [POST /users]
*Cadastra um novo usuário e manda um email de boas vindas para o seu email cadastrado*

+ Request (application/json)
    + Attributes
        <!-- include(../../requests/userStore.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../responses/userStore.apib) -->

+ Response 400 (aplication/json)
    + Attributes
        <!-- include(../../util/errorBadRequest.apib) -->
