+ `_id`: 5e05d818a46bb07bfe789a9f
+ address: `Edifício Alcione Zago - Av. César Finotti, 305 - Jardim Finotti, Uberlândia - MG, 38400-165, Brasil`
+ geo_location (object)
    + lat: `-18.9238301`
    + lng: `-48.2592808`
+ local_name: Edifício Alcione Zago
+ `__v`: 0
