+ addresses (array)
  + (object)
      + `_id`: 5e05d7c573b8727b1e14273e
      + address: `Rua, Av. Floriano Peixoto, 1615 - Nossa Sra. Aparecida, Uberlândia - MG, 38400-706, Brasil`
      + geo_location (object)
          + lat: `-18.9104354`
          + lng: `-48.270157`
      + local_name: T10 Lab
      + created_at: `2019-12-27T10:07:01.590Z`
      + updated_at: `2019-12-27T10:07:01.590Z`
      + `__v`: 0
  + (object)
      + `_id`: 5e05d818a46bb07bfe789a9f
      + address: `Edifício Alcione Zago - Av. César Finotti, 305 - Jardim Finotti, Uberlândia - MG, 38400-165, Brasil`
      + geo_location (object)
          + lat: `-18.9238301`
          + lng: `-48.259280`
      + local_name: Edifício Alcione Zago
      + `__v`: 0
  + (object)
      + `_id`: 5e0641a183ae076445a437d6
      + address: `Rua, Av. Floriano Peixoto, 1615 - Nossa Sra. Aparecida, Uberlândia - MG, 38400-706, Brasil`
      + geo_location (object)
          + lat: `-18.9104354`
          + lng: `-48.270157`
      + local_name: T10 Lab
      + `__v`: 0

