+ (array)
    + (object)
        + `_id`: 5e0644551d47aa674f87aa01
        + user: 5e063e0c3a37285c4a4665db
        + address: (object)
            + `_id`: 5e0644551d47aa674f87aa00
            + address: `Rua, Av. Floriano Peixoto, 1615 - Nossa Sra. Aparecida, Uberlândia - MG, 38400-706, Brasil`
            + geo_location: (object)
                + lat: `-18.9104354`
                + lng: `-48.270157`
            + local_name: T10 Lab
            + `__v`: 0
        + first_name: Gabriel
        + last_name: Maximo
        + cpf: 12345678914
        + created_at: `2019-12-27T17:50:13.607Z`
        + updated_at: `2019-12-27T17:50:13.607Z`
        + `__v`: +
    + (object)
        + `_id`: 5e0644551d47aa674f87aa01
        + user: 5e063e0c3a37285c4a4665db
        + address: (object)
            + `_id`: 5e0644551d47aa674f87aa00
            + address: `Rua, Av. Floriano Peixoto, 1615 - Nossa Sra. Aparecida, Uberlândia - MG, 38400-706, Brasil`
            + geo_location: (object)
                + lat: `-18.9104354`
                + lng: `-48.270157`
            + local_name: T10 Lab
            + `__v`: 0
        + first_name: Gabriel
        + last_name: Maximo
        + cpf: 12345678914
        + created_at: `2019-12-27T17:50:13.607Z`
        + updated_at: `2019-12-27T17:50:13.607Z`
        + `__v`: 0
