FORMAT: 1A

# T10 LAB Backend Challenge
#### By *_Gabriel Maximo_*
#### Base URL - *_https://t10lab.herokuapp.com_*

<!-- include(routes/users/index.apib) -->
<!-- include(routes/sessions/index.apib) -->
<!-- include(routes/people/index.apib) -->
<!-- include(routes/addresses/index.apib) -->
